### PR TITLE
Add pr checklist

### PR DESCRIPTION
**Pull request by dshiga**
I was assigned an action item in retro a long time ago to make a PR checklist.

See https://elastc.com/c/7I0aV0nQ/643-pr-checklist

### CODE REVIEW

**Comment by dshiga** [comment]
retest this please

**Comment by rexwangcc** [comment]
How about put the template file in a `.github/` dir to make it invisible?

**Comment by dshiga** [comment]
retest this please

**Comment by dshiga** [comment]
retest this please

**Pull request merged**
