### PR TITLE
Update analysis outputs in SmartSeq2 Adapter WDL 

### PR DESCRIPTION
**Pull request by samanehsan**
The SmartSeq2 analysis WDL outputs will change with this PR: https://github.com/HumanCellAtlas/skylab/pull/126 and the adapter WDL needs to be updated accordingly to pass those outputs to the submit subworkflow. 

Note: Merge along with updates to the new SS2 analysis WDL in skylab so that the mintegration test passes!

### CODE REVIEW

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
^ The mintegration test is currently failing because it is not using the latest bundle version, but this passed when testing locally with a new bundle.

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
This mintegration test is failing because the lira config generated in the test needs to include `GroupMetricsOutputs.wdl` under the files required for SS2. This is added in this PR: https://github.com/HumanCellAtlas/secondary-analysis/pull/311

**Comment by rexwangcc** [comment]
@jishuxu

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Pull request merged**
