### PR TITLE
Fix analysis protocol linking issue

### PR DESCRIPTION
**Pull request by rexwangcc**
See: https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/223

Please ensure the following when opening a PR:
- [x] Added or updated tests
- [ ] Updated documentation
- [x] Applied style guidelines
- [x] Considered generalizability beyond our own use case

### CODE REVIEW

**Comment by samanehsan** [comment]
These integration tests failed because it could not find the image in quay...but the test built and pushed the pipeline-tools image 🤔

**Comment by samanehsan** [comment]
Retest this please

**Comment by samanehsan** [comment]
Please resolve the version conflicts with the pipeline-tools image! I incremented the version in the cellranger adapter wdl in my PR that I just merged in :octocat:

**Comment by rexwangcc** [comment]
retest this my jenkins!

**Comment by rexwangcc** [comment]
retest this please

**Comment by rexwangcc** [comment]
@samanehsan Thanks! Per the discussion with @aaclan-ebi I will:
- Rebase to clean the commit history
- Change the tags in WDLs to v0.38.0
- Switch to use `self` than get_subject_url.

**Pull request merged**
