### PR TITLE
Switch to get the version of the pipelines from WDL and update HCA metadata schemas

### PR DESCRIPTION
**Pull request by rexwangcc**
This PR need to wait for https://github.com/HumanCellAtlas/skylab/pull/127 to be merged first. 

Please ensure the following when opening a PR:
- [ ] Added or updated tests
- [ ] Updated documentation
- [ ] Applied style guidelines
- [ ] Considered generalizability beyond our own use case

### CODE REVIEW

**Comment by samanehsan** [comment]
Can you bring this PR up to date with the master branch?

**Comment by samanehsan** [comment]
Ah I approved too soon! Can you look into the failing travis tests please?

**Comment by rexwangcc** [comment]
@samanehsan Sorry it failed because I forgot to change the variables in `patch()` after refactoring. I'm going to rebase onto master to include the latest changes dave merged in.

**Comment by rexwangcc** [comment]
@samanehsan Just finished the scavenger work and updating to a set of new schema versions, it'd be appreciated if you could take another look!

**Comment by rexwangcc** [comment]
The mintegration test is passing locally on this branch and Skylab branch `cw-hard-code-pipeline-versions-in-wdls`, the corresponding workflow is `1d9a9782-4541-48ec-801c-092859723538` in CaaS-dev, I think we can merge in this PR now.

**Comment by rexwangcc** [comment]
retest this please

**Comment by rexwangcc** [comment]
retest this please

**Comment by rexwangcc** [comment]
I'm going to merge this PR, but I probably don't want to use this version of pipeline-tools until we have a tagged version of SS2!

**Pull request merged**
