### PR TITLE
Remove unused gtf_file parameter from SS2 adapter

### PR DESCRIPTION
**Pull request by mckinsel**

### CODE REVIEW

**Comment by mckinsel** [comment]
Also see HumanCellAtlas/skylab#149

**Comment by samanehsan** [comment]
Hey @mckinsel! The Jenkins Integration tests will test the changes from branches in pipeline-tools, skylab and lira together if they have the same branch name (otherwise it uses what is on the master branch). So if you change this branch from `mckinsel-remove-usused-input` --> `mckinsel-remove-unused-input` to match the name of your branch in Skylab the test should pass.

**Comment by samanehsan** [comment]
Can you also remove the `gtf_file` from the test analysis.json file here? https://github.com/HumanCellAtlas/pipeline-tools/blob/c6c11a20c91aa360fcd7ca7c28de14b281cabd7b/pipeline_tools/tests/data/analysis_process.json#L28

**Comment by mckinsel** [comment]
Thanks @samanehsan ! Closing in favor of #109

**Pull request closed without merging**
