### PR TITLE
Add "schema_url" parameter for creating the analysis JSON

### PR DESCRIPTION
**Pull request by samanehsan**
Please ensure the following when opening a PR:
- [ ] Added or updated tests
- [ ] Updated documentation
- [ ] Applied style guidelines
- [ ] Considered generalizability beyond our own use case

### CODE REVIEW

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by samanehsan** [comment]
retest this please

**Comment by rexwangcc** [comment]
I personally prefer using `int` schemas even for our `dev`, so we won't get blocked by potential breaking changes on their end, what do you think?

**Comment by samanehsan** [comment]
Sounds good to me @rexwangcc! I changed the default for "dev" lira to use the HCA integration schemas in this [PR](https://github.com/HumanCellAtlas/lira/pull/89/files), and since it is a part of the Lira config we should be able to change this if we need to test with a different configuration!

**Comment by rexwangcc** [comment]
That looks good to me! Thanks!

**Pull request merged**
